// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnbs-DJanRecVld_XlmMRA8_aX4QzF-Ro',
    appId: '1:746355663921:web:b77f31b3b91c67a57da110',
    messagingSenderId: '746355663921',
    projectId: 'mediconnect-9b5ae',
    authDomain: 'mediconnect-9b5ae.firebaseapp.com',
    storageBucket: 'mediconnect-9b5ae.firebasestorage.app',
    measurementId: 'G-5TLFQYVC18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNmfMr4dteLiGHh82j__aVKL-26BtFwCg',
    appId: '1:746355663921:android:da5443f517fba9497da110',
    messagingSenderId: '746355663921',
    projectId: 'mediconnect-9b5ae',
    storageBucket: 'mediconnect-9b5ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ59As4rCeonqebZNWJid2O82xco77cR8',
    appId: '1:746355663921:ios:f075726ee0e2da5b7da110',
    messagingSenderId: '746355663921',
    projectId: 'mediconnect-9b5ae',
    storageBucket: 'mediconnect-9b5ae.firebasestorage.app',
    iosBundleId: 'com.example.mediconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ59As4rCeonqebZNWJid2O82xco77cR8',
    appId: '1:746355663921:ios:f075726ee0e2da5b7da110',
    messagingSenderId: '746355663921',
    projectId: 'mediconnect-9b5ae',
    storageBucket: 'mediconnect-9b5ae.firebasestorage.app',
    iosBundleId: 'com.example.mediconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnbs-DJanRecVld_XlmMRA8_aX4QzF-Ro',
    appId: '1:746355663921:web:9440e6373c88bacb7da110',
    messagingSenderId: '746355663921',
    projectId: 'mediconnect-9b5ae',
    authDomain: 'mediconnect-9b5ae.firebaseapp.com',
    storageBucket: 'mediconnect-9b5ae.firebasestorage.app',
    measurementId: 'G-E4M5G5FNSP',
  );
}
