// lib/my_prescriptions_page.dart
import 'dart:typed_data'; // Needed for PDF data
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:mediconnect/auth_service.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart'; // PDF package
import 'package:pdf/widgets.dart' as pw; // PDF package (aliased)
import 'package:printing/printing.dart'; // Printing package

class MyPrescriptionsPage extends StatelessWidget {
  MyPrescriptionsPage({super.key});

  final AuthService _authService = AuthService();
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // --- Function to generate and save PDF ---
  Future<void> _generateAndSavePdf(
      BuildContext context, Map<String, dynamic> data) async {
    final pdf = pw.Document();

    // Extract data for PDF
    final doctorName = data['doctorName'] ?? 'Unknown Doctor';
    final patientName =
        data['patientName'] ?? 'Patient Name Unknown'; // Get patient name
    final List<dynamic> medicationsList = data['medications'] ?? [];
    final notes = data['notes'] ?? 'No additional notes';
    final issuedAt = (data['issuedAt'] as Timestamp?)?.toDate();
    final formattedDate = issuedAt != null
        ? DateFormat('EEE, MMM d, yyyy').format(issuedAt)
        : 'Date unknown';

    // Build the PDF content
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context pdfContext) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(30),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header
                pw.Header(
                  level: 0,
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text('MediConnect Prescription',
                          style: pw.TextStyle(
                              fontSize: 24, fontWeight: pw.FontWeight.bold)),
                      pw.Text(formattedDate,
                          style: const pw.TextStyle(fontSize: 12)),
                    ],
                  ),
                ),
                pw.Divider(thickness: 2),
                pw.SizedBox(height: 20),

                // Patient and Doctor Info
                pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text('Patient: $patientName',
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text('Prescribed by: $doctorName',
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    ]),
                pw.SizedBox(height: 30),

                // Medications Table
                pw.Text('Medications:',
                    style: pw.TextStyle(
                        fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                if (medicationsList.isNotEmpty)
                  pw.Table.fromTextArray(
                    headers: ['Medication', 'Dosage'],
                    data: medicationsList.map((med) {
                      final medMap = med as Map<String, dynamic>? ?? {};
                      return [
                        medMap['medication'] ?? 'N/A',
                        medMap['dosage'] ?? 'N/A'
                      ];
                    }).toList(),
                    border: pw.TableBorder.all(),
                    headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    cellAlignment: pw.Alignment.centerLeft,
                    cellPadding: const pw.EdgeInsets.all(5),
                  )
                else
                  pw.Text('No medications listed.'),
                pw.SizedBox(height: 30),

                // Notes
                if (notes.isNotEmpty) ...[
                  pw.Text('Notes / Instructions:',
                      style: pw.TextStyle(
                          fontSize: 16, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 5),
                  pw.Text(notes),
                ],

                pw.Spacer(), // Push footer to bottom
                pw.Divider(),
                pw.Text('This prescription was generated by MediConnect.',
                    style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
              ],
            ),
          );
        },
      ),
    );

    // Use the printing package to save or share the PDF
    try {
      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
      );
    } catch (e) {
      print("Error generating or saving PDF: $e");
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error generating PDF: $e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }
  // --- END OF PDF FUNCTION ---

  @override
  Widget build(BuildContext context) {
    final user = _authService.currentUser;
    if (user == null) {
      return const Scaffold(
          body: Center(child: Text('You must be logged in.')));
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('My Prescriptions'),
        backgroundColor: Theme.of(context).primaryColor,
        foregroundColor: Colors.white,
      ),
      body: StreamBuilder<QuerySnapshot>(
        stream: _firestore
            .collection('prescriptions')
            .where('patientId', isEqualTo: user.uid)
            .orderBy('issuedAt', descending: true)
            .snapshots(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasError) {
            if (snapshot.error.toString().contains('index')) {
              // Show index error message
              return const Center(
                child: Padding(
                  padding: EdgeInsets.all(24.0),
                  child: Text(
                    'Firestore Error:\n\nThe required index for this query is missing.\n\nPlease check the VS Code DEBUG CONSOLE for a link to create it automatically in Firebase.',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: Colors.red, fontSize: 16),
                  ),
                ),
              );
            }
            return Center(child: Text('Error: ${snapshot.error}'));
          }
          if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
            // Show no prescriptions message
            return const Center(
              child: Text(
                'You have no prescriptions.',
                style: TextStyle(fontSize: 18, color: Colors.grey),
              ),
            );
          }

          final prescriptions = snapshot.data!.docs;

          return ListView.builder(
            padding: const EdgeInsets.all(16.0),
            itemCount: prescriptions.length,
            itemBuilder: (context, index) {
              final doc = prescriptions[index];
              final data = doc.data() as Map<String, dynamic>;

              // Extract prescription details
              final doctorName = data['doctorName'] ?? 'Unknown Doctor';
              final List<dynamic> medicationsList = data['medications'] ?? [];
              final notes = data['notes'] ?? 'No additional notes';
              final issuedAt = (data['issuedAt'] as Timestamp?)?.toDate();
              final formattedDate = issuedAt != null
                  ? DateFormat('EEE, MMM d, yyyy').format(issuedAt)
                  : 'Date unknown';

              return Card(
                elevation: 3.0,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12.0),
                ),
                margin: const EdgeInsets.only(bottom: 16.0),
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Flexible(
                            child: Text(
                              'Prescription', // Main title
                              style: const TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 18,
                              ),
                            ),
                          ),
                          Text(
                            formattedDate,
                            style: TextStyle(
                                color: Colors.grey[600], fontSize: 13),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Prescribed by: $doctorName',
                        style: TextStyle(
                          color: Theme.of(context).primaryColor,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const Divider(height: 20),

                      // Loop through and display medications
                      if (medicationsList.isNotEmpty)
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: medicationsList.map((med) {
                            final medMap = med as Map<String, dynamic>? ?? {};
                            final medName = medMap['medication'] ?? 'N/A';
                            final medDosage = medMap['dosage'] ?? 'N/A';
                            return Padding(
                              padding: const EdgeInsets.only(bottom: 8.0),
                              child: Row(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Icon(Icons.medication_outlined,
                                      size: 18, color: Colors.green[700]),
                                  const SizedBox(width: 8),
                                  Expanded(
                                      child: Text('$medName - $medDosage',
                                          style:
                                              const TextStyle(fontSize: 15))),
                                ],
                              ),
                            );
                          }).toList(),
                        )
                      else
                        const Text('No medications listed.',
                            style: TextStyle(fontStyle: FontStyle.italic)),

                      const SizedBox(height: 16),
                      if (notes.isNotEmpty) ...[
                        const Text('Notes:',
                            style: TextStyle(fontWeight: FontWeight.bold)),
                        const SizedBox(height: 4),
                        Text(
                          notes,
                          style:
                              TextStyle(fontSize: 14, color: Colors.grey[700]),
                        ),
                      ],

                      // --- THIS IS THE SAVE PDF BUTTON ---
                      const SizedBox(height: 16),
                      Align(
                        alignment: Alignment.centerRight,
                        child: TextButton.icon(
                          icon: Icon(Icons.picture_as_pdf_outlined,
                              color: Theme.of(context).primaryColor),
                          label: Text('Save as PDF',
                              style: TextStyle(
                                  color: Theme.of(context).primaryColor)),
                          // --- Make sure onPressed calls the function ---
                          onPressed: () => _generateAndSavePdf(context, data),
                        ),
                      ),
                      // --- END OF BUTTON ---
                    ],
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
